
# The name of your website.
name: Portfolio Stijn van Cuijk

description:

  # Description of your site. This will show up in google.
  meta: Portfolio site van Stijn van Cuijk, aspirerend ontwerper op het gebied van product, graphic en web design.

author:
  name: Stijn van Cuijk # Change this!

  # Necessary for contact page
  email: contact@stijn.vc # Change this!

# The URL of the homepage of your site (without trailing slash). Leave this
# empty when you run Jekyll locally.
url: http://localhost:4000
baseurl: ""

# language attribute in <html> element.
lang: nl_NL

# FROM THIS POINT ON EVERYTHING IS OPTIONAL

##############
# APPEREANCE #
##############

# Toolbar color for Chrome on Android.
theme-color-attr: "#fa4343"

# Color of Microsoft live Tile.
ms-tile-color: "#fa4343"

# Number of posts on each page.
paginate: 100


################
# SOCIAL ICONS #
################

# Use a complete url here, including http:// and such. Requiring just usernames
# has been considered, but this is way more customizable.
twitter:
youtube:
instagram:
tumblr:
facebook:
google-plus:
reddit:
soundcloud:
medium:
linkedin: https://nl.linkedin.com/in/stijnvancuijk
github: https://github.com/steinvc/
behance: https://www.behance.net/stijnvc
codepen: http://codepen.io/steinvc/pens/popular/
dribbble:
trello:
stack-overflow:
bitcoin:
paypal:


##################
# BUILD SETTINGS #
##################

# You don't have to change these.

exclude: [vendor]
highlighter: pygments
kramdown:
  input: GFM
paginate_path: "/page-:num/"
permalink: pretty
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "portfolio-page"
